package org.example.jfinal.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSystemConfig<M extends BaseSystemConfig<M>> extends Model<M> implements IBean {

	/**
	 * 配置id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 配置id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * uuid
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}
	
	/**
	 * uuid
	 */
	public java.lang.String getUuid() {
		return getStr("uuid");
	}
	
	/**
	 * 系统配置名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 系统配置名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 缓存key
	 */
	public void setCode(java.lang.String code) {
		set("code", code);
	}
	
	/**
	 * 缓存key
	 */
	public java.lang.String getCode() {
		return getStr("code");
	}
	
	/**
	 * 配置项
	 */
	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	/**
	 * 配置项
	 */
	public java.lang.String getValue() {
		return getStr("value");
	}
	
	/**
	 * 类型
0-字符串
1-数组
2-json对象
3-数字
4-布尔值
5-加密
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 类型
0-字符串
1-数组
2-json对象
3-数字
4-布尔值
5-加密
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 是否启用此配置
0-不启用
1-启用
	 */
	public void setEnable(java.lang.Integer enable) {
		set("enable", enable);
	}
	
	/**
	 * 是否启用此配置
0-不启用
1-启用
	 */
	public java.lang.Integer getEnable() {
		return getInt("enable");
	}
	
	/**
	 * 配置介绍
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 配置介绍
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 创建者
	 */
	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	/**
	 * 创建者
	 */
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	/**
	 * 修改时间
	 */
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

