package org.example.jfinal.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePermission<M extends BasePermission<M>> extends Model<M> implements IBean {

	/**
	 * 权限id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 权限id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * uuid
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}
	
	/**
	 * uuid
	 */
	public java.lang.String getUuid() {
		return getStr("uuid");
	}
	
	/**
	 * 权限组id
	 */
	public void setGroupId(java.lang.String groupId) {
		set("group_id", groupId);
	}
	
	/**
	 * 权限组id
	 */
	public java.lang.String getGroupId() {
		return getStr("group_id");
	}
	
	/**
	 * 权限名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 权限名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 权限字符串
	 */
	public void setValue(java.lang.String value) {
		set("value", value);
	}
	
	/**
	 * 权限字符串
	 */
	public java.lang.String getValue() {
		return getStr("value");
	}
	
	/**
	 * 权限描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 权限描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 权限类型-字典表
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 权限类型-字典表
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 创建者id
	 */
	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}
	
	/**
	 * 创建者id
	 */
	public java.lang.String getCreator() {
		return getStr("creator");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	/**
	 * 修改时间
	 */
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

