package org.example.jfinal.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	/**
	 * 用户自增id
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 用户自增id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 用户id
	 */
	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}
	
	/**
	 * 用户id
	 */
	public java.lang.String getUuid() {
		return getStr("uuid");
	}
	
	/**
	 * 用户来源服务
	 */
	public void setService(java.lang.String service) {
		set("service", service);
	}
	
	/**
	 * 用户来源服务
	 */
	public java.lang.String getService() {
		return getStr("service");
	}
	
	/**
	 * 账户
	 */
	public void setAccount(java.lang.String account) {
		set("account", account);
	}
	
	/**
	 * 账户
	 */
	public java.lang.String getAccount() {
		return getStr("account");
	}
	
	/**
	 * 邮箱
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	/**
	 * 邮箱
	 */
	public java.lang.String getEmail() {
		return getStr("email");
	}
	
	/**
	 * 手机号
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}
	
	/**
	 * 密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * 账号状态
0-未激活
1-正常
2-密码冻结
3-违规
4-注销
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 账号状态
0-未激活
1-正常
2-密码冻结
3-违规
4-注销
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 头像
	 */
	public void setHeader(java.lang.String header) {
		set("header", header);
	}
	
	/**
	 * 头像
	 */
	public java.lang.String getHeader() {
		return getStr("header");
	}
	
	/**
	 * 磁盘id
	 */
	public void setDisk(java.lang.String disk) {
		set("disk", disk);
	}
	
	/**
	 * 磁盘id
	 */
	public java.lang.String getDisk() {
		return getStr("disk");
	}
	
	/**
	 * 昵称
	 */
	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}
	
	/**
	 * 昵称
	 */
	public java.lang.String getNickname() {
		return getStr("nickname");
	}
	
	/**
	 * 性别
0-未知
1-男
2-女
	 */
	public void setGender(java.lang.Integer gender) {
		set("gender", gender);
	}
	
	/**
	 * 性别
0-未知
1-男
2-女
	 */
	public java.lang.Integer getGender() {
		return getInt("gender");
	}
	
	/**
	 * 个性签名
	 */
	public void setSignature(java.lang.String signature) {
		set("signature", signature);
	}
	
	/**
	 * 个性签名
	 */
	public java.lang.String getSignature() {
		return getStr("signature");
	}
	
	/**
	 * 登录ip
	 */
	public void setLoginIp(java.lang.String loginIp) {
		set("login_ip", loginIp);
	}
	
	/**
	 * 登录ip
	 */
	public java.lang.String getLoginIp() {
		return getStr("login_ip");
	}
	
	/**
	 * 最后登陆时间
	 */
	public void setLastLoginTime(java.util.Date lastLoginTime) {
		set("last_login_time", lastLoginTime);
	}
	
	/**
	 * 最后登陆时间
	 */
	public java.util.Date getLastLoginTime() {
		return getDate("last_login_time");
	}
	
	/**
	 * 密码错误次数,最大为五
	 */
	public void setPasswordErrorNum(java.lang.Integer passwordErrorNum) {
		set("password_error_num", passwordErrorNum);
	}
	
	/**
	 * 密码错误次数,最大为五
	 */
	public java.lang.Integer getPasswordErrorNum() {
		return getInt("password_error_num");
	}
	
	/**
	 * 登录时常,最大12
	 */
	public void setOnlineTime(java.lang.Integer onlineTime) {
		set("online_time", onlineTime);
	}
	
	/**
	 * 登录时常,最大12
	 */
	public java.lang.Integer getOnlineTime() {
		return getInt("online_time");
	}
	
	/**
	 * 用户积分
	 */
	public void setScore(java.lang.Integer score) {
		set("score", score);
	}
	
	/**
	 * 用户积分
	 */
	public java.lang.Integer getScore() {
		return getInt("score");
	}
	
	/**
	 * 用户所在城市,默认是未知
	 */
	public void setAddress(java.lang.Integer address) {
		set("address", address);
	}
	
	/**
	 * 用户所在城市,默认是未知
	 */
	public java.lang.Integer getAddress() {
		return getInt("address");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatedAt(java.util.Date createdAt) {
		set("created_at", createdAt);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatedAt() {
		return getDate("created_at");
	}
	
	/**
	 * 修改时间
	 */
	public void setUpdatedAt(java.util.Date updatedAt) {
		set("updated_at", updatedAt);
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdatedAt() {
		return getDate("updated_at");
	}
	
}

