package org.example.jfinal.system.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRolePermission<M extends BaseRolePermission<M>> extends Model<M> implements IBean {

	/**
	 * 用户角色中间表
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 用户角色中间表
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 角色
	 */
	public void setRole(java.lang.String role) {
		set("role", role);
	}
	
	/**
	 * 角色
	 */
	public java.lang.String getRole() {
		return getStr("role");
	}
	
	/**
	 * 权限
	 */
	public void setPermission(java.lang.String permission) {
		set("permission", permission);
	}
	
	/**
	 * 权限
	 */
	public java.lang.String getPermission() {
		return getStr("permission");
	}
	
}

