package org.example.jfinal.system.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("permission", "id", Permission.class);
		arp.addMapping("permission_group", "id", PermissionGroup.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("role_permission", "id", RolePermission.class);
		arp.addMapping("system_config", "id", SystemConfig.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("user_role", "id", UserRole.class);
		arp.addMapping("user_status_log", "id", UserStatusLog.class);
	}
}


