package org.example.jfinal.system.model;

import org.example.jfinal.system.model.base.BasePermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permission extends BasePermission<Permission> {
	public static final Permission dao = new Permission().dao();
}

