package org.example.jfinal.system.model;

import org.example.jfinal.system.model.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role().dao();
}

