package org.example.jfinal.system.model;

import org.example.jfinal.system.model.base.BaseSystemConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SystemConfig extends BaseSystemConfig<SystemConfig> {
	public static final SystemConfig dao = new SystemConfig().dao();
}

