package org.example.jfinal.system.model;

import org.example.jfinal.system.model.base.BaseUserStatusLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserStatusLog extends BaseUserStatusLog<UserStatusLog> {
	public static final UserStatusLog dao = new UserStatusLog().dao();
}

